// Auto-generated by deploy script
import { type Address } from 'viem';

export const CONTRACTS = {
  vault: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512' as Address,
  nexToken: '0x5FbDB2315678afecb367f032d93F642f64180aa3' as Address,
  tokens: [
    { address: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9' as Address, symbol: 'WETH', name: 'Wrapped Ether', decimals: 18 },
    { address: '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9' as Address, symbol: 'USDC', name: 'USD Coin', decimals: 6 },
    { address: '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707' as Address, symbol: 'DAI', name: 'Dai Stablecoin', decimals: 18 },
    { address: '0x0165878A594ca255338adfa4d48449f69242Eb8F' as Address, symbol: 'WBTC', name: 'Wrapped Bitcoin', decimals: 8 },
  ] as { address: Address; symbol: string; name: string; decimals: number }[],
};

export const TOKEN_COLORS = {
  WETH: '#F59E0B',
  USDC: '#F59E0B',
  DAI: '#F59E0B',
  WBTC: '#F59E0B',
};
