const hre = require('hardhat');
const fs = require('fs');
const path = require('path');

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log('Deploying with account:', deployer.address);
  console.log('Balance:', (await hre.ethers.provider.getBalance(deployer.address)).toString());

  // 1. Deploy NexusToken
  console.log('\n[1/6] Deploying NexusToken...');
  const NexusToken = await hre.ethers.getContractFactory('NexusToken');
  const nexToken = await NexusToken.deploy();
  await nexToken.waitForDeployment();
  const nexTokenAddress = await nexToken.getAddress();
  console.log('  NexusToken deployed to:', nexTokenAddress);

  // 2. Deploy NexusVault
  console.log('\n[2/6] Deploying NexusVault...');
  const currentBlock = await hre.ethers.provider.getBlockNumber();
  const NexusVault = await hre.ethers.getContractFactory('NexusVault');
  const vault = await NexusVault.deploy(nexTokenAddress, currentBlock + 1);
  await vault.waitForDeployment();
  const vaultAddress = await vault.getAddress();
  console.log('  NexusVault deployed to:', vaultAddress);

  // 3. Set Vault as minter for NEX token
  console.log('\n[3/6] Setting Vault as NEX minter...');
  await (await nexToken.addMinter(vaultAddress)).wait();
  console.log('  Vault is now a NEX minter');

  // 4. Deploy Mock ERC20 tokens
  console.log('\n[4/6] Deploying Mock ERC20 tokens...');
  const MockERC20 = await hre.ethers.getContractFactory('MockERC20');

  const tokens = [
    { name: 'Wrapped Ether', symbol: 'WETH', decimals: 18, supply: '100000' },
    { name: 'USD Coin', symbol: 'USDC', decimals: 6, supply: '100000000' },
    { name: 'Dai Stablecoin', symbol: 'DAI', decimals: 18, supply: '100000000' },
    { name: 'Wrapped Bitcoin', symbol: 'WBTC', decimals: 8, supply: '1000' },
  ];

  const tokenAddresses = [];
  for (const t of tokens) {
    const token = await MockERC20.deploy(
      t.name,
      t.symbol,
      t.decimals,
      hre.ethers.parseUnits(t.supply, t.decimals)
    );
    await token.waitForDeployment();
    const addr = await token.getAddress();
    tokenAddresses.push({ ...t, address: addr, contract: token });
    console.log(`  ${t.symbol} deployed to:`, addr);
  }

  // 5. Add pools to Vault
  console.log('\n[5/6] Adding pools to Vault...');
  const allocPoints = [300, 400, 200, 100]; // WETH, USDC, DAI, WBTC
  for (let i = 0; i < tokenAddresses.length; i++) {
    await (await vault.addPool(tokenAddresses[i].address, allocPoints[i])).wait();
    console.log(`  Pool ${i}: ${tokenAddresses[i].symbol} - allocPoint: ${allocPoints[i]}`);
  }

  // 6. Send some test tokens to the deployer
  console.log('\n[6/6] Sending test tokens to deployer...');
  for (const t of tokenAddresses) {
    const faucetAmount = hre.ethers.parseUnits(
      t.symbol === 'WETH' ? '10' : t.symbol === 'WBTC' ? '0.5' : '10000',
      t.decimals
    );
    await (await t.contract.transfer(deployer.address, faucetAmount)).wait();
    console.log(`  Sent ${hre.ethers.formatUnits(faucetAmount, t.decimals)} ${t.symbol} to deployer`);
  }

  // Write deployment addresses to frontend config
  console.log('\n=== DEPLOYMENT COMPLETE ===');
  console.log('Vault:', vaultAddress);
  console.log('NEX Token:', nexTokenAddress);
  tokenAddresses.forEach(t => console.log(`${t.symbol}:`, t.address));

  // Save deployment info
  const deploymentInfo = {
    chainId: (await hre.ethers.provider.getNetwork()).chainId.toString(),
    deployer: deployer.address,
    vault: vaultAddress,
    nexToken: nexTokenAddress,
    tokens: tokenAddresses.map(t => ({
      symbol: t.symbol,
      name: t.name,
      decimals: t.decimals,
      address: t.address,
    })),
    timestamp: new Date().toISOString(),
  };

  const deployPath = path.join(__dirname, '../deployments/localhost.json');
  fs.mkdirSync(path.dirname(deployPath), { recursive: true });
  fs.writeFileSync(deployPath, JSON.stringify(deploymentInfo, null, 2));
  console.log('\nDeployment info saved to:', deployPath);

  // Also update frontend config
  const frontendConfigPath = path.join(__dirname, '../../src/config/contracts.ts');
  const frontendConfig = `// Auto-generated by deploy script
import { type Address } from 'viem';

export const CONTRACTS = {
  vault: '${vaultAddress}' as Address,
  nexToken: '${nexTokenAddress}' as Address,
  tokens: [
${tokenAddresses.map(t => `    { address: '${t.address}' as Address, symbol: '${t.symbol}', name: '${t.name}', decimals: ${t.decimals} },`).join('\n')}
  ] as { address: Address; symbol: string; name: string; decimals: number }[],
};

export const TOKEN_COLORS = {
${tokenAddresses.map(t => `  ${t.symbol}: '${t.color || '#F59E0B'}',`).join('\n')}
};
`;
  fs.writeFileSync(frontendConfigPath, frontendConfig);
  console.log('Frontend config updated:', frontendConfigPath);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
